### ISSUE TITLE
[Bug]: Build from source code don't show the light/dark mode in navigation bar

### ISSUE THREAD

**Issue by koiker** [cloudscape-design/demos#132]
### Browser

Chrome

### Package version

v3.0.0

### React version

v20.10.0

### Description

Cloning the repo and following the instructions to build and start the demos.
Opening the local server and opening the form.html that is the single page demo.
The navigation bar doesn't have the light mode | dark mode as the Cloudscape website shows.
The source-code doesn't reflect the demo running on Cloudscape website.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/demos/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/demos/issues) for duplicate problems

**Comment by jperals** [comment]
Hi Rafael,

This is true, the top bar toggles are added only in the Cloudscape website and they are not part of this repository code. Can you describe what you are trying to do and why you would need this feature?

**Comment by koiker** [comment]
Hey Joan,
I was just looking for a code snippet of the toggle function.
I built a toggle function using the navigation menu and the JS helpers provided in the documentation. I asked about the code because the demos show the functionality, but when I cloned the source and tried to run, I couldn't find the code snippet for it.

**Comment by DavidSouther** [comment]
Could someone share the resolution? I came to this page because the docs link here to see how to implement the visual mode toggle.

**Comment by jperals** [comment]
Hi David,

Sorry for the delay in the answer. The `@cloudscape-design/global-styles `package provides an API for applying color (light vs dark) as well as density mode (compact vs comfortable) and disabling motion: https://cloudscape.design/get-started/integration/global-styles

A simple light/dark mode toggle could be implemented like this:

```
import { applyMode, Mode } from '@cloudscape-design/global-styles';

const ColorModeToggle = () => {
    const [mode, setMode] = useState(Mode.Light);
    
    useEffect(() => applyMode(mode), [mode]);

    return (
        <Toggle
            checked={mode === Mode.Dark}
            onChange={({ detail }) => setMode(detail.checked ? Mode.Dark : Mode.Light)}>
            Dark mode
        </Toggle>
    );
};
```

**Comment by jperals** [comment]
Do you mean the settings at the OS or the browser level? Sure, that makes sense. In that case you should be able to detect the setting with browser APIs: https://stackoverflow.com/a/57795518, and use the globalStyles API to sync the color mode in the Cloudscape app accordingly.

**Comment by DavidSouther** [comment]
Yes, I know how to use globalStyles. I would find cloudscape, the design system, more valuable as a tool if it took responsibility for this. Using that approach will fail to apply opposite-mode styling on first paint, so users will get flashed with light mode content until matchMedia finishes & react has an opportunity to rerender Cloudscape.
