### ISSUE TITLE
[Feature Request]:  Make demo apps with Laravel and/or Supabase

### ISSUE THREAD

**Issue by abeatbeyondlab** [cloudscape-design/demos#133]
### Description

Laravel and Supabase are both really famous headless backend frameworks.

I am sure that some examples with supabase/laravel, especially using tables can boost the adoption of cloudscape framework

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/demos/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/demos/issues) for duplicate requests

**Comment by abdhalees** [comment]
Hi abeatbeyondlab, 

Our components are only available in React, if your app uses React in the frontend you should be able to use the source code from our demos. e.g. https://cloudscape.design/examples/react/table.html

**Comment by abeatbeyondlab** [comment]
I am talking about making react examples using supabase or laravel like is doing refine.dev

**Comment by abdhalees** [comment]
Our demos are purely client side with some mocked server side demos.

From the [supabase React guide](https://supabase.com/docs/guides/getting-started/quickstarts/reactjs) you can use our components in `App.js` as they are in the demos, the data fetching part is specific to supabase but it shouldn't impact how are components are used.

which part of our demos is not clear how to use with  supabase?

**Comment by abeatbeyondlab** [comment]
an advise: for more adoption make templates for supabase..

**Comment by gethinwebster** [comment]
Thanks for the feedback and for opening this request. This is unfortunately something that we're unlikely to work on as it doesn't align with our long-term vision - we prefer to provide generic examples that can be applied in many different scenarios rather than demos that are specific to 3rd party integrations.
